name: Add USB Image to Release

on:
  release:
    types:
      - published

jobs:
  add-usb-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create USB Image
        run: |
            sudo apt-get install grub-efi-amd64 parted kpartx
            chmod +x ./create-usb-image.sh
            sudo ./create-usb-image.sh ${{ github.event.release.tag_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/fos-usb.img
